# Profiling csv generated from `stations` object
2023-01-24  
alcthach@gmail.com

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../src/python_scripts/stations/data_file.csv')

In [3]:
df_stations = pd.read_csv('../src/python_scripts/stations/stations.csv')

In [4]:
df_stations

,physical_configuration,rental_uris,lon,cross_street,groups,nearby_distance,name,altitude,address,is_charging_station,capacity,lat,_ride_code_support,rental_methods,post_code,obcn,station_id
0,REGULAR,{},-79.395954,NaN,[],500.0,Fort York Blvd / Capreol Ct,0.0,Fort York Blvd / Capreol Ct,False,35,43.639832,True,"['KEY', 'TRANSITCARD', 'CREDITCARD', 'PHONE']",NaN,647-643-9607,7000
1,ELECTRICBIKESTATION,{},-79.383550,NaN,[],500.0,Wellesley Station Green P,0.0,Yonge / Wellesley,True,26,43.664964,True,"['KEY', 'TRANSITCARD', 'CREDITCARD', 'PHONE']",M4Y 1G7,416-617-9576,7001
2,REGULAR,{},-79.399429,NaN,[],500.0,St. George St / Bloor St W,0.0,St. George St / Bloor St W,False,19,43.667333,True,"['KEY', 'TRANSITCARD', 'CREDITCARD', 'PHONE']",NaN,647-643-9615,7002
3,REGULAR,{},-79.402761,NaN,[],500.0,Madison Ave / Bloor St W,NaN,Madison Ave / Bloor St W,False,15,43.667158,True,"['KEY', 'TRANSITCARD', 'CREDITCARD', 'PHONE']",NaN,647-631-4587,7003
4,REGULAR,{},-79.389099,NaN,['P7004-7047'],500.0,University Ave / Elm St,NaN,University Ave / Elm St,False,11,43.656518,True,"['KEY', 'TRANSITCARD', 'CREDITCARD', 'PHONE']",NaN,647-643-9673,7004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,ELECTRICBIKESTATION,{},-79.394635,NaN,[],350.0,The Well,0.0,The Well,True,18,43.642890,True,"['KEY', 'TRANSITCARD', 'CREDITCARD', 'PHONE']",M5V 2H6,NaN,7757
649,VAULT,{},-79.516278,NaN,[],1000.0,Driftwood Ave / Finch Hydro Trail,0.0,Driftwood Ave / Finch Hydro Trail,False,18,43.760362,True,"['KEY', 'TRANSITCARD', 'PHONE']",M3N 2N4,NaN,7758
650,VAULT,{},-79.511912,NaN,[],350.0,The Pond Rd / Shoreham Dr,0.0,1804 Ian Macdonald Boulevard,False,15,43.772445,True,"['KEY', 'TRANSITCARD', 'PHONE']",M3J 3M4,NaN,7759
651,VAULT,{},-79.491800,NaN,[],350.0,Grand Avenue Park,0.0,45 Grand Avenue,False,22,43.623130,True,"['KEY', 'TRANSITCARD', 'PHONE']",M8Y 0A7,NaN,7760
652,REGULAR,{},-79.370638,NaN,[],350.0,Moss Park,0.0,152 Shuter Street,False,15,43.655972,True,"['KEY', 'TRANSITCARD', 'CREDITCARD', 'PHONE']",M5A 1V9,NaN,7761